apiVersion: v2
name: argocd-subchart
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: argo-cd
  version: 5.32.2
  repository: https://argoproj.github.io/argo-helm
- name: argocd-apps
  version: 1.0.1
  repository: https://argoproj.github.io/argo-helm
