argo-cd:
  global:
    deploymentStrategy:
      type: RollingUpdate
  dex:
    enabled: false
argocd-apps:
  applications:
  - name: argocd-applicationsets
    namespace: argocd
    project: infrastructure
    source:
      repoURL: https://github.com/fmbahrt/tooling-playground.git
      targetRevision: HEAD
      path: argocd/applicationsets
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true

  projects:
  - name: infrastructure
    namespace: argocd
    description: For everything infrastructure related
    sourceRepos:
    - '*'
    destinations:
    - namespace: '*'
      server: '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
