apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/fmbahrt/tooling-playground.git
      revision: HEAD
      directories:
      - path: cluster-addons/*/*
  template:
    metadata:
      name: '{{path[1]}}-{{path[2]}}'
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/fmbahrt/tooling-playground.git
        path: '{{path}}'
        targetRevision: HEAD
      destination:
        namespace: '{{path[1]}}'
        name: '{{path[2]}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
