name: Cluster Addons Synchronize

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: "false"
        required: false
  push:
    branches: ["main"]

jobs:
  synchronize:
    name: Synchronize
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.1

      - name: Synchronize
        run: |
          docker pull public.ecr.aws/docker/library/redis:7.0.11-alpine
          python .github/synchronize_images.py
